FROM python:3.12-slim

WORKDIR /app

COPY src/api/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src/api/ ./
COPY resources/ /resources/

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
