/**
 * Quran Multi-Language Mobile App — React Native Starter
 *
 * Features:
 * - Offline SQLite database (generated by scripts/generate_sqlite.py)
 * - Audio streaming with download for offline
 * - Bookmarking and last-read position
 * - Dark/light theme
 *
 * Setup:
 *   1. Run `python scripts/generate_sqlite.py` to generate quran.db
 *   2. Copy quran.db to the app's assets directory
 *   3. npm install && npx react-native run-android (or run-ios)
 */

import React from "react";
import {
  View,
  Text,
  FlatList,
  TouchableOpacity,
  StyleSheet,
  useColorScheme,
} from "react-native";

interface Surah {
  number: number;
  name: string;
  name_en: string;
  verses: number;
  revelation_type: string;
}

const SAMPLE_SURAHS: Surah[] = [
  { number: 1, name: "الفاتحة", name_en: "Al-Fatihah", verses: 7, revelation_type: "Meccan" },
  { number: 2, name: "البقرة", name_en: "Al-Baqarah", verses: 286, revelation_type: "Medinan" },
  { number: 3, name: "آل عمران", name_en: "Aal-e-Imran", verses: 200, revelation_type: "Medinan" },
  { number: 36, name: "يس", name_en: "Ya-Sin", verses: 83, revelation_type: "Meccan" },
  { number: 55, name: "الرحمن", name_en: "Ar-Rahman", verses: 78, revelation_type: "Medinan" },
  { number: 67, name: "الملك", name_en: "Al-Mulk", verses: 30, revelation_type: "Meccan" },
  { number: 112, name: "الإخلاص", name_en: "Al-Ikhlas", verses: 4, revelation_type: "Meccan" },
  { number: 114, name: "الناس", name_en: "An-Nas", verses: 6, revelation_type: "Meccan" },
];

export default function App() {
  const colorScheme = useColorScheme();
  const isDark = colorScheme === "dark";
  const theme = isDark ? darkTheme : lightTheme;

  const renderSurah = ({ item }: { item: Surah }) => (
    <TouchableOpacity
      style={[styles.surahCard, { backgroundColor: theme.card }]}
      activeOpacity={0.7}
    >
      <View style={[styles.surahNumber, { backgroundColor: theme.primary }]}>
        <Text style={styles.surahNumberText}>{item.number}</Text>
      </View>
      <View style={styles.surahInfo}>
        <View style={styles.surahNameRow}>
          <Text style={[styles.surahNameEn, { color: theme.text }]}>
            {item.name_en}
          </Text>
          <Text style={[styles.surahNameAr, { color: theme.text }]}>
            {item.name}
          </Text>
        </View>
        <Text style={[styles.surahMeta, { color: theme.secondary }]}>
          {item.verses} verses · {item.revelation_type}
        </Text>
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={[styles.container, { backgroundColor: theme.background }]}>
      <View style={styles.header}>
        <Text style={[styles.bismillah, { color: theme.primary }]}>
          بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ
        </Text>
        <Text style={[styles.title, { color: theme.text }]}>
          Quran Multi-Language
        </Text>
        <Text style={[styles.subtitle, { color: theme.secondary }]}>
          Read, Listen, and Learn
        </Text>
      </View>

      <FlatList
        data={SAMPLE_SURAHS}
        keyExtractor={(item) => String(item.number)}
        renderItem={renderSurah}
        contentContainerStyle={styles.list}
      />
    </View>
  );
}

const lightTheme = {
  background: "#ffffff",
  card: "#f5f5f5",
  text: "#1a1a1a",
  secondary: "#666666",
  primary: "#0f766e",
};

const darkTheme = {
  background: "#0a0a0a",
  card: "#1a1a1a",
  text: "#ededed",
  secondary: "#999999",
  primary: "#2e8b57",
};

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { alignItems: "center", paddingTop: 60, paddingBottom: 20 },
  bismillah: { fontSize: 24, fontWeight: "600", marginBottom: 8 },
  title: { fontSize: 22, fontWeight: "bold" },
  subtitle: { fontSize: 14, marginTop: 4 },
  list: { paddingHorizontal: 16 },
  surahCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  surahNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  surahNumberText: { color: "#fff", fontWeight: "bold", fontSize: 14 },
  surahInfo: { flex: 1 },
  surahNameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  surahNameEn: { fontSize: 16, fontWeight: "600" },
  surahNameAr: { fontSize: 18 },
  surahMeta: { fontSize: 12, marginTop: 4 },
});
